### ISSUE TITLE
Prebuilt Docker image

### ISSUE THREAD

**Issue by petrleocompel** [Just-Moh-it/Pckd#32]
For further use docker images would be amazing (that we do not have to build each version on our machnies).

So I made an example (even with 2 containers - better than nothing) in fork https://github.com/petrleocompel/Pckd

Result = 2 images
https://hub.docker.com/r/petrleocompel/pckd-client
https://hub.docker.com/r/petrleocompel/pckd-server

Used Github Actions + 2 Actions secrets `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`.
How to make a DockerHub token -> https://docs.docker.com/docker-hub/access-tokens/

I can make a pull request (only thing to tweak is change name of docker images).

Otherwise it is done.

**Comment by petrleocompel** [comment]
My tweaked yaml after that
```yaml
version: "3"

services:
  server:
    image: petrleocompel/pckd-server
    volumes:
      - ./logs:/home/node/app/logs
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/pckd
      - DATABASE_TYPE=postgres
      - JWT_SECRET= verysecurestring
      - IPREGISTRY_API_KEY=f1ntkcjoqaazglj7
    depends_on:
      - db

  frontend:
    image: petrleocompel/pckd-client
    ports:
      - 80:80
    environment:
      - BACKEND_URL=http://server:4000

  db:
    image: postgres:13-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pckd
```
